name: FormWarps
version: ${version}
main: ru.rexlite.warps.WarpMain
api: [1.1.0]
description: Warp system for your server with UI Forms.
author: Criex
permissions:
  formwarps.commands.setwarp:
    default: op
  formwarps.commands.delwarp:
    default: op
  formwarps.commands.delwarp.others:
    default: op
  formwarps.commands.warp:
    default: true
  formwarps.commands.warps:
    default: true
